server:
  port: 8087

spring:
  application:
   name: ai-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/fitnessrecommendation
      Database: fitnessrecommendation


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
