server:
  port: 8085


spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/fitnessapp_user_db
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto : update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true

  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka




